---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider: 
    name: libvirt
    type: libvirt
  parallel: true
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7-test
    box: centos/7
    memory: 1024
    cpus: 1
  - name: centos8-test
    box: centos/8
    memory: 1024
    cpus: 1
  - name: debian11-test
    box: debian/bullseye64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: ansible
